name: "Build"
description: "Executes a compilation."

runs:
  using: "composite"
  steps:
      - name: Compile
        shell: bash
        run: |
          SRC_FOLDER=$(pwd)

          mkdir -p build && cd build
          cmake -DSRC_FOLDER=${SRC_FOLDER} -DRUN_COVERAGE=1 -DRUN_TESTS=1 .. && make -j2

          echo "Running command: cmake -DSRC_FOLDER=${SRC_FOLDER} -GNinja -DRUN_COVERAGE=1 -DRUN_TESTS=1 .. && ninja"
